/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/common/ActionButton.vue')['default']
    CheckUpdateButton: typeof import('./src/components/update/CheckUpdateButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MainLayout: typeof import('./src/components/layouts/MainLayout.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateDisplay: typeof import('./src/components/common/StateDisplay.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    TrainerCard: typeof import('./src/components/common/TrainerCard.vue')['default']
    TrainerSkeleton: typeof import('./src/components/common/TrainerSkeleton.vue')['default']
    UpdateDialog: typeof import('./src/components/update/UpdateDialog.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    WindowLayout: typeof import('./src/components/layouts/WindowLayout.vue')['default']
  }
}
